name: Bug report
description: Report a bug in berserk
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        <b>Thank you for reporting an issue. Before submitting, please [search existing issues](https://github.com/lichess-org/berserk/issues) to confirm this is not a duplicate issue.</b>
  - type: textarea
    attributes:
      label: Describe the issue
      description: Provide what happened, what went wrong, and what you expected to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: Provide precise step by step instructions on how to reproduce the bug
    validations:
      required: true
  - type: input
    attributes:
      label: Berserk version
      description: Specify the version of berserk you are using
    validations:
      required: true
    validations:
      required: true
  - type: input
    attributes:
      label: Python version
      description: Specify the version of python you are using
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      description: Specify the OS you are using
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Provide any additional information that will give more context for the issue you are encountering.
        Screenshots can be added by clicking this area and then pasting or dragging them in.
    validations:
      required: false
