#!/bin/bash -e

IMAGE=ghcr.io/lichess-org/lila-docker:ci

cleanup_containers() {
    docker rm --force lila > /dev/null 2>&1 || true
    docker rm --force app > /dev/null 2>&1 || true
    docker network rm lila-network > /dev/null 2>&1 || true
}

echo "Running integration tests"
cleanup_containers

docker network create lila-network
docker run --name lila --network lila-network -d $IMAGE
docker run --name app --network lila-network -v $(pwd):/app -w /app $IMAGE ./integration/run-tests.sh

cleanup_containers
echo "✅ Done"
